[package]
name = "whatsapp-rust"
version = "1.0.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
dotenvy = "0.15.7"
lazy_static = "1.5.0"
reqwest = { version = "0.13.4", features = ["json", "multipart", "stream"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["time"] }
time = { version = "0.3", features = ["formatting", "macros"] }
